//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vohmencev_Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.BorrowingOfBooks = new HashSet<BorrowingOfBooks>();
        }
    
        public int BookCode { get; set; }
        public string BookName { get; set; }
        public Nullable<int> BookAuthor { get; set; }
        public Nullable<int> BookPublisher { get; set; }
        public string BookGenres { get; set; }
        public string BookAvialability { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Publishers Publishers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BorrowingOfBooks> BorrowingOfBooks { get; set; }
    }
}
