//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vohmencev_Library.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowingOfBooks
    {
        public int BorrowingNumber { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> LibraryUser { get; set; }
        public Nullable<System.DateTime> DateSince { get; set; }
        public Nullable<System.DateTime> DateUntil { get; set; }
        public string BorrowingStatus { get; set; }
    
        public virtual Books Books { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
